version: '3.9'

services:
  brain-ag:
    build:
      context: ../
      dockerfile: ./compose/brain-ag/Dockerfile
    container_name: brain_ag_api
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - backend

  db:
    build:
      context: ./db
    image: postgres:17
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - backend


volumes:
  pgdata:

networks:
  backend: