version: '3.9'

services:
  db:
    build:
      context: ./db
    image: postgres:17
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - backend

  # brain-ag:
  #   build:
  #     context: ./brain-ag
  #   container_name: brain_ag_api
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@db:5432/brain_ag_db
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - backend

volumes:
  pgdata:

networks:
  backend: